package com.example.cartservice_dec.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Document
@NoArgsConstructor
@AllArgsConstructor
public class CartItem {
    @Id
    private int id; // Automatically generated by MongoDB
    private String userId;
    private String productId;
    private int noOfProducts;
}
